### PR TITLE
Initial Content

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by mmlb** [comment]
Not sure if I want to drop gomnd and wsl in this PR or a follow up, I think follow up...?

**Comment by joelrebel** [comment]
@mmlb, would prefer if this was based this off https://github.com/metal-toolbox/mctl/blob/main/.golangci.yml#L1-L90
since we've been curating it for a while and theres a bunch of autofixes included.

**Comment by mmlb** [comment]
Alright @joelrebel, @DoctorVin I've updated the config file to be based off of mctl's. There were some invalid configs, cargo culted settings and unnecessary disables that I've removed/tweaked. Both mctl and ironlib will need some tweaks to pass with this config but imo they are worth doing. mctl is pretty good, ironlib needs the most work (mostly mechanical). I'll post a PR to each with the changes necessary to work with this config in a little bit.

It would probably be easier to review each commit on its own, I made it so it would be easier to trust the changes/diff if reviewed that way.

**Comment by mmlb** [comment]
mctl: https://github.com/metal-toolbox/mctl/pull/108

**Review by joelrebel — APPROVED** [review]
Thanks for the efforts here. 

Before we PR changes to the other projects, we can have this repo provide a reusable GH workflow that others import. And the reusable workflow could verify a project linter configuration does not differ from the one here. I can take this up.

**Pull request merged**
